#if !DISABLE_MBUG
// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters
{
    public sealed class UnityLogEntryFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::UnityLogEntry>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::UnityLogEntry value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(11);
            writer.Write(value.idx);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.content, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.stacktrace, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::LogType>(formatterResolver).Serialize(ref writer, value.logType, options);
            writer.Write(value.utcRealTimeTicks);
            writer.Write(value.realTimeFromStartTicks);
            writer.Write(value.scaledTime);
            writer.Write(value.frame);
            writer.Write(value.fixedUpdateTick);
            writer.Write(value.bgVideoFrame);
            writer.Write(value.bgVideoTime);
        }

        public global::UnityLogEntry Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::UnityLogEntry();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.idx = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.content = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.stacktrace = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.logType = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::LogType>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.utcRealTimeTicks = reader.ReadInt64();
                        break;
                    case 5:
                        ____result.realTimeFromStartTicks = reader.ReadInt64();
                        break;
                    case 6:
                        ____result.scaledTime = reader.ReadDouble();
                        break;
                    case 7:
                        ____result.frame = reader.ReadInt32();
                        break;
                    case 8:
                        ____result.fixedUpdateTick = reader.ReadInt32();
                        break;
                    case 9:
                        ____result.bgVideoFrame = reader.ReadInt32();
                        break;
                    case 10:
                        ____result.bgVideoTime = reader.ReadDouble();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
#endif
