#if !DISABLE_MBUG
// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters
{
    public sealed class UnityFrameDataFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::UnityFrameData>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::UnityFrameData value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            writer.WriteArrayHeader(8);
            writer.WriteNil();
            writer.Write(value.frame);
            writer.Write(value.fullFrameDuration);
            writer.Write(value.behaviourUpdateDuration);
            writer.Write(value.fixedUpdatesDuration);
            writer.Write(value.fixedUpdatesCount);
            writer.Write(value.bgVideoFrame);
            writer.Write(value.bgVideoTime);
        }

        public global::UnityFrameData Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var length = reader.ReadArrayHeader();
            var ____result = new global::UnityFrameData();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 1:
                        ____result.frame = reader.ReadInt32();
                        break;
                    case 2:
                        ____result.fullFrameDuration = reader.ReadSingle();
                        break;
                    case 3:
                        ____result.behaviourUpdateDuration = reader.ReadSingle();
                        break;
                    case 4:
                        ____result.fixedUpdatesDuration = reader.ReadSingle();
                        break;
                    case 5:
                        ____result.fixedUpdatesCount = reader.ReadInt32();
                        break;
                    case 6:
                        ____result.bgVideoFrame = reader.ReadInt32();
                        break;
                    case 7:
                        ____result.bgVideoTime = reader.ReadDouble();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
#endif
